# Form implementation generated from reading ui file 'd:\Third Semester files\database\project POSHAAK final\POSHAAK-database\login form.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(561, 650)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 30, 501, 521))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(-10, 30, 561, 531))
        self.label.setStyleSheet("border-image: url(background.jpeg);\n"
"border-radius: 25px;")
        self.label.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(200, 90, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgba(0,0,0,1);\n"
"")
        self.label_3.setObjectName("label_3")
        self.userName = QtWidgets.QLineEdit(parent=self.widget)
        self.userName.setGeometry(QtCore.QRect(140, 160, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.userName.setFont(font)
        self.userName.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:3px solid rgba(155,158,152,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-top:5px;\n"
"padding-bottom:2px;\n"
"")
        self.userName.setObjectName("userName")
        self.password = QtWidgets.QLineEdit(parent=self.widget)
        self.password.setGeometry(QtCore.QRect(140, 250, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:3px solid rgba(155,158,152,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-top:5px;\n"
"padding-bottom:2px;\n"
"")
        self.password.setInputMask("")
        self.password.setPlaceholderText("Password")
        self.password.setObjectName("password")
        self.loginbutton = QtWidgets.QPushButton(parent=self.widget)
        self.loginbutton.setGeometry(QtCore.QRect(150, 340, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loginbutton.setFont(font)
        self.loginbutton.setStyleSheet("QPushButton#pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(250, 150, 100, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 240);\n"
"    border-radius:5px;\n"
"\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(250, 130, 100, 220), stop:1 rgba(105, 118, 132, 226));\n"
"\n"
"}\n"
"QPushButton#pushButton:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200);\n"
"}")
        self.loginbutton.setCheckable(False)
        self.loginbutton.setObjectName("loginbutton")
        self.signupbutton = QtWidgets.QPushButton(parent=self.widget)
        self.signupbutton.setGeometry(QtCore.QRect(170, 400, 171, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.signupbutton.setFont(font)
        self.signupbutton.setStyleSheet("QPushButton#pushButton_3{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(250, 150, 100, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 240);\n"
"    border-radius:5px;\n"
"\n"
"}\n"
"QPushButton#pushButton_3:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(250, 130, 100, 220), stop:1 rgba(105, 118, 132, 226));\n"
"\n"
"}\n"
"QPushButton#pushButton_3:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200);\n"
"}")
        self.signupbutton.setObjectName("signupbutton")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 521, 481))
        self.label_2.setStyleSheet("background-color:rgba(0,0,0,120);\n"
"border-radius: 15px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.adminCheck = QtWidgets.QCheckBox(parent=self.widget)
        self.adminCheck.setGeometry(QtCore.QRect(390, 320, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.adminCheck.setFont(font)
        self.adminCheck.setAutoFillBackground(True)
        self.adminCheck.setObjectName("adminCheck")
        self.label_2.raise_()
        self.label.raise_()
        self.userName.raise_()
        self.password.raise_()
        self.loginbutton.raise_()
        self.signupbutton.raise_()
        self.label_3.raise_()
        self.adminCheck.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 561, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "LOGIN"))
        self.userName.setPlaceholderText(_translate("MainWindow", "User Name"))
        self.loginbutton.setText(_translate("MainWindow", "Login"))
        self.signupbutton.setText(_translate("MainWindow", "Sign up"))
        self.adminCheck.setText(_translate("MainWindow", "Admin"))
