# Form implementation generated from reading ui file 'd:\Third Semester files\database\project POSHAAK final\POSHAAK-database\signup_Form.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 771)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 381, 471))
        self.label.setStyleSheet("border-image: url(:/images/signupImage.jpeg);\n"
"border-top-left-radius:50px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.firstname = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.firstname.setGeometry(QtCore.QRect(440, 310, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.firstname.setFont(font)
        self.firstname.setStyleSheet("background-color:rgba(0,0,0,170);\n"
"border:none;\n"
"border-bottom:3px solid rgba(155,158,152,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-top:5px;\n"
"padding-bottom:2px;\n"
"")
        self.firstname.setObjectName("firstname")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 381, 471))
        self.label_4.setStyleSheet("background-color:rgba(0,0,0,80);\n"
"border-top-left-radius: 50px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.lastname = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lastname.setGeometry(QtCore.QRect(440, 380, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lastname.setFont(font)
        self.lastname.setStyleSheet("background-color:rgba(0,0,0,170);\n"
"border:none;\n"
"border-bottom:3px solid rgba(155,158,152,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-top:5px;\n"
"padding-bottom:2px;\n"
"")
        self.lastname.setText("")
        self.lastname.setObjectName("lastname")
        self.email = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.email.setGeometry(QtCore.QRect(440, 180, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.email.setFont(font)
        self.email.setStyleSheet("background-color:rgba(0,0,0,170);\n"
"border:none;\n"
"border-bottom:3px solid rgba(155,158,152,255);\n"
"color: rgba(255,255,255,240);\n"
"padding-top:5px;\n"
"padding-bottom:2px;\n"
"")
        self.email.setText("")
        self.email.setObjectName("email")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(440, 230, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color:rgba(0,0,0,170);\n"
"border:none;\n"
"border-bottom:3px solid rgba(155,158,152,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-top:5px;\n"
"padding-bottom:2px;\n"
"")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.pass.setGeometry(QtCore.QRect(440, 450, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pass.setFont(font)
        self.pass.setStyleSheet("background-color:rgba(0,0,0,170);\n"
"border:none;\n"
"border-bottom:3px solid rgba(155,158,152,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-top:5px;\n"
"padding-bottom:2px;\n"
"")
        self.pass.setText("")
        self.pass.setObjectName("pass")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(520, 100, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgba(0,0,0,210);\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 60, 351, 471))
        self.label_2.setStyleSheet("background-color:rgba(255,255,255,255);\n"
"border-bottom-right-radius: 50px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.firstname.raise_()
        self.lastname.raise_()
        self.email.raise_()
        self.lineEdit_4.raise_()
        self.pass.raise_()
        self.label_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.firstname.setPlaceholderText(_translate("MainWindow", "First Name"))
        self.lastname.setPlaceholderText(_translate("MainWindow", "Last Name"))
        self.email.setPlaceholderText(_translate("MainWindow", "User Email"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Verification Code"))
        self.pass.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label_5.setText(_translate("MainWindow", "Sign Up"))
