# Form implementation generated from reading ui file 'd:\Third Semester files\database\project POSHAAK final\POSHAAK-database\App\DeliveryInsert.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 110, 101, 21))
        self.label.setObjectName("label")
        self.CityLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.CityLineEdit.setGeometry(QtCore.QRect(150, 110, 261, 20))
        self.CityLineEdit.setObjectName("CityLineEdit")
        self.AreaLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.AreaLineEdit.setGeometry(QtCore.QRect(150, 150, 261, 20))
        self.AreaLineEdit.setObjectName("AreaLineEdit")
        self.CountryLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.CountryLineEdit.setGeometry(QtCore.QRect(150, 190, 261, 20))
        self.CountryLineEdit.setObjectName("CountryLineEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 101, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 190, 101, 21))
        self.label_3.setObjectName("label_3")
        self.InsertButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.InsertButton.setGeometry(QtCore.QRect(500, 350, 81, 31))
        self.InsertButton.setObjectName("InsertButton")
        self.PostalLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.PostalLineEdit.setGeometry(QtCore.QRect(150, 230, 261, 20))
        self.PostalLineEdit.setObjectName("PostalLineEdit")
        self.ChargesLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ChargesLineEdit.setGeometry(QtCore.QRect(150, 270, 261, 20))
        self.ChargesLineEdit.setObjectName("ChargesLineEdit")
        self.PossibleLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.PossibleLineEdit.setGeometry(QtCore.QRect(150, 310, 261, 20))
        self.PossibleLineEdit.setObjectName("PossibleLineEdit")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 230, 101, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 310, 101, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 270, 101, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(200, 20, 231, 31))
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "City"))
        self.label_2.setText(_translate("MainWindow", "Area"))
        self.label_3.setText(_translate("MainWindow", "Country"))
        self.InsertButton.setText(_translate("MainWindow", "Insert"))
        self.label_4.setText(_translate("MainWindow", "Postal Code"))
        self.label_5.setText(_translate("MainWindow", "Is Possible?"))
        self.label_6.setText(_translate("MainWindow", "Charges"))
        self.label_7.setText(_translate("MainWindow", "Insert New Delivery Area"))
